---

- hosts: tnode2-ubuntu.exp.com
  vars:
    logdir: /var/log/daily_log
    logfile: todays.log
  
  tasks:
    - name: Configuare Log Env
      block:
        - name: (block) Find Directory
          ansible.builtin.find:
            paths: "{{ logdir }}"
          register: result
          failed_when: "'Not all paths' in result.msg"
    
      rescue:
        - name: (rescue) Make Diretory when Not found Directory
          ansible.builtin.file:
            path: "{{ logdir }}"
            state: directory
            mode: '0755'
      
      always:
        - name: (always) Create File
          ansible.builtin.file:
            path: "{{ logdir }}/{{ logfile }}"
            state: touch
            mode: '0644'