---
- hosts: tnode2-ubuntu.exp.com
  force_handlers: yes

  tasks: 
    - name: restart rsyslog
      ansible.builtin.service:
        name: "rsyslog"
        state: restarted
      notify:
        - print msg
  
    - name: Install apache2
      ansible.builtin.dnf:
        name: apache2
        state: latest
  
  handlers:
    - name: print msg
      ansible.builtin.debug:
        msg: "rsyslog is restarted"